### ISSUE TITLE
ERROR in Module.createRequire is not a function

### ISSUE THREAD

**Issue by flop-code** [coder8080/warplay.cloud#1]
Project starts with error page:
`Html Webpack Plugin:
  Error: Child compilation failed:
  Module.createRequire is not a function`
[Screenshot](https://ibb.co/12kj1hj)
Same logs in terminal.
Steps to install and run (followed from readme):
1. git clone ...
2. npm i
3. npm start

**Comment by coder8080** [comment]
Good day.
What node version do you use?
Check with `node -v` please

**Comment by flop-code** [comment]
**I solved my issue** with updating node to latest version from official website.
I had v10.21.0 previously. It's to old.

**Comment by coder8080** [comment]
Ok.
Tip: you can use [nvm](https://github.com/nvm-sh/nvm) to easily control your node version.
